package encryptionDecryption;


import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.util.Base64;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;

/**
 * Class for AES-256 encryption and decryption of Strings using the CBC Mode with a constant IV
 * 
 * @author Lukas Dentler
 */
public class AES256 {
	
	//generating constant IV
	private static final byte[] BYTE_IV = {42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42};
	private static final IvParameterSpec IV = new IvParameterSpec(BYTE_IV);
	private static final String ALGORITHM_WITH_PADDING = "AES/CBC/PKCS5Padding";
	
	/**
	 * Encrypts the given plain text String using the AES-256 CBC algorithm and a suitable key
	 * 
	 * @param strPlaintext the plain text that should be encrypted
	 * @param strKey either a key generated by KeyGenerator for AES-256 and then encrypted to String with Base64
	 * 		  or a bit string with 256 bits
	 * @return A String containing the encrypted plain text, In case of an Error returns null
	 */
	public static String encrypt(String strPlaintext, String strKey) {
		
		//converting plain text to byteArray
		byte[] bytePlaintext = strPlaintext.getBytes(StandardCharsets.UTF_8);
		
		//generating SecretKey from String
		SecretKey key = CryptoUtility.stringToSecretKeyAES256(strKey);
		
		try {
			//get Cipher Instance
			Cipher cipher = Cipher.getInstance(ALGORITHM_WITH_PADDING);
			
			//initialize Cipher for encryption
			cipher.init(Cipher.ENCRYPT_MODE, key, IV);
			
			//perform encryption
			byte[] byteCiphertext = cipher.doFinal(bytePlaintext);
			
			//convert cipher text to string
			String strCiphertext = Base64.getEncoder().encodeToString(byteCiphertext);
			
			return strCiphertext;
		}
		//printing exceptions
		catch (InvalidKeyException e) {
			System.err.println("An invalid Key was used. \n" + e.toString());
		}
		catch (IllegalBlockSizeException e) {
			System.err.println("The plaintext has the wrong length. \n" + e.toString());
		}
		catch (Exception e) {
			//TODO later printing exception to UI
			System.err.println("An ERROR occured during encryption:\n" + e.toString());
		}
		return null ;
	}
	
	
	/**
	 * Decrypts the given cipher text String using the AES-256 CBC algorithm and the corresponding key used to encrypt the cipher text
	 * 
	 * @param strCiphertext the cipher text that should be decrypted
	 * @param strKey the key used to encrypt the cipher text
	 * @return A String containing the decrypted cipher text 
	 */
	public static String decrypt(String strCiphertext, String strKey) {
		
		//converting cipher text to byteArray
		byte[] byteCiphertext = Base64.getDecoder().decode(strCiphertext);
		
		//generating SecretKey from String
		SecretKey key = CryptoUtility.stringToSecretKeyAES256(strKey);
		
		try {
			//get Cipher Instance
			Cipher cipher = Cipher.getInstance(ALGORITHM_WITH_PADDING);
			
			//initialize Cipher for decryption
			cipher.init(Cipher.DECRYPT_MODE, key, IV);		
			
			//perform decryption
			byte[] bytePlaintext = cipher.doFinal(byteCiphertext);
			
			//convert plain text to string
			String strPlaintext = new String(bytePlaintext, StandardCharsets.UTF_8);
			//String strPlaintext = Base64.getEncoder().encodeToString(bytePlaintext);
			
			return strPlaintext;
		}
		//printing exceptions
		catch (InvalidKeyException e) {
			System.err.println("An invalid Key was used. \n" + e.toString());
		}
		catch (IllegalBlockSizeException e) {
			System.err.println("The ciphertext has the wrong length, make sure to decrypt only text that has been encrypted first \n" + e.toString());
		}
		catch (BadPaddingException e) {
			System.err.println("An ERROR occured regarding the padding of the encrypted text. \n A common reason for this ERROR is that a different key was used for encryption and decryption\n" + e.toString());
		}
		catch (Exception e) {
			//TODO later printing exception to UI
			System.err.println("An ERROR occured during decryption:\n" + e.toString());
		}
		return null;
	}
	
	
}
