package encryptionDecryption;

import java.util.Base64;

import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

/**
 * Utility for conversion of different inputs into byte arrays and Secret Keys
 * 
 * @author Lukas Dentler
 */
public class CryptoUtility {

	private final static int BIT_STRING_LENGTH_AES256 = 256;
	private final static String ALGORITHM_AES = "AES";
	private final static int STRING_LENGTH_GENERATED_KEY_AES256 = 44;
	
	/**
	 * Used to convert a bit string containing 256 bits into an byteArray containing 32 bytes
	 * 
	 * @param str A String containing 256 bits(0 or 1);
	 * @return A byteArray containing 32 bytes corresponding to the 256 bits of str
	 * 		   returns null if str is not fulfilling the contracted specification.
	 */
	public static byte[] bitString256ToByteArray32(String str) {
		
		byte[] bytes = new byte[32];
		int j = 0;
		
		if (str.length() != BIT_STRING_LENGTH_AES256) {
			System.out.println("Please only use 256 char long bit strings");
			return null;
		}
		
		//converting bits from bitString into bytes that can be put into a byteArray
		for(int i=0; i < 32; i++) {
			bytes[j] = (byte) (Integer.valueOf(str.substring(i * 8, i * 8 + 8), 2) - 128);
			j++;
		}
		return bytes;
	}
	
	/**
	 * Used to convert a String with key data to a SecretKey object usable with javax.crypto.Cipher
	 * 
	 * @param str either a key generated by KeyGenerator for AES and then encrypted to String with Base64 or a bitString with 256 bits
	 * @return An instance of SecretKey used to encrypt or decrypt with javax.crypto.Cipher
	 * 		   returns null if str is not fulfilling the contracted specification.
	 */
	public static SecretKey stringToSecretKeyAES256(String str) {

		if (str.length() != BIT_STRING_LENGTH_AES256 && str.length() != STRING_LENGTH_GENERATED_KEY_AES256) {
			System.out.println("An invalid key was used. Please use either a key generated by KeyGenerator for AES and then encrypted to String with Base64 or a bitString with 256 bits");
			return null;
		}
		
		byte[] byteKey;
		
		//deciding whether strKey is a bitString or generated String for Key
		if(str.length() == BIT_STRING_LENGTH_AES256) {
			byteKey = bitString256ToByteArray32(str);
		}
		else {
			byteKey = Base64.getDecoder().decode(str);
		}
		
		//wrapping key information in SecretKey class for AES 
		return new SecretKeySpec(byteKey, 0, byteKey.length, ALGORITHM_AES);
	}
	
}
